- name: Fix filesystem rights
  file:
    path:    '{{ item.path }}'
    state:   directory
    mode:    0775
    owner:   'vagrant'
    group:   'vagrant'
    recurse: '{{ item.recurse }}'
  with_items:
   - { path: '/home/vagrant/.config/', recurse: 'yes' }
   - { path: '/usr/local/bin/',        recurse: 'yes' }
   - { path: '/var/www/',              recurse: 'no' }
