#- name: Add docker key
#  apt_key: url=https://get.docker.io/gpg state=present

#- name: Add docker repository
#  apt_repository:
#    repo: 'deb http://get.docker.io/ubuntu docker main'
#    update_cache: yes
#    state: present

#- name: Install docker
#  action: apt pkg='{{ item }}' state=latest
#  with_items:
#    - lxc-docker

#- name: Add docker group
#  group: name=docker gid=999 state=present

#- name: Add docker user
#  user: name=docker comment="Docker" uid=999 group=docker

- name: Install docker
  action: apt pkg='{{ item }}' state=latest
  with_items:
    - lxc-docker
